### PR TITLE
Consolidate to get and set the encryptKey (SCRD-8061)

### PR DESCRIPTION
**Pull request by ghost**
This commit includes:

1. Added a global var gEncryptKey and a set of
helper functions getCachedEncryptKey and setCachedEncryptKey.

2. The gEncryptKey will be shared among pages where it needs
to run playbooks with encryptKey.

3. Updated replace controller, replace compute, add compute,
activate/deactivate/delete compute to use helper functions
when it needs to deal with encryptKey.

4. Updated service info, package and configuration to use
helper functions when it needs to deal with encryptKey

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
tried without the encryption key and this seems to be fine, need to test with it enabled (or at least faked)

**Comment by guglo** [comment]
To test is_encrypted API call in development env, from ardana-service dir
mkdir data/ardana-ansible/group_vars
echo '$ANSIBLE_VAULT;1.1;AES256' >data/ardana-ansible/group_vars/all --> to test true
echo '1.1;AES256' > data/ardana-ansible/group_vars/all --> test false
Not sure where to put this instruction permanently though.

**Review by jeremy-moffitt — APPROVED** [review]
tried this out on my local dev system with the encryption key setting enabled, behaved as expected

**Review by eapodaca — APPROVED** [review]
LGTM

**Pull request merged**
