### PR TITLE
SCRD-5073 update Day0/2 UI to use 4.x bootstrap

### PR DESCRIPTION
**Pull request by jeremy-moffitt**
Github identified a security issue with the version of bootstrap we were using. Unfortunately switching to BS4 required some minor refactoring and slightly changes the look & feel of the UI. The changes are pretty minor. When this merges it will be necessary to update IBS in parallel with an updated tarball of the dependencies.

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
updated to fix the example pages... I probably should've made it a separate commit so you could see just those changes, sorry!

**Comment by GarySmith** [comment]
This examples page is still kinda borked. If you change the radius, then the graph doesn't resize properly. Since this is only an example page, there could be worse things, but it makes me wonder whether we can even use these components with bootstrap4.

**Comment by jeremy-moffitt** [comment]
I'll take another swing at it... I didnt muck with the settings of the example components much, just made the initial layout look right :-/  oops!

**Comment by jeremy-moffitt** [comment]
fixed! and I got to learn about ` height: fit-content;`

**Comment by GarySmith** [comment]
That worked for me. Gloria is still testing it.

**Comment by guglo** [comment]
@jeremy-moffitt  Found a couple of issues, please take a look: 
1. messages are not closable .
2.  error message is blue. You can observe it a couple of places, one is in login page where invalid login message pops up. 
2. success message is blue. You can observe it in discover connection test. It seem to have a bug related to enable buttons , but it has nothing to do with styling. I will enter a defect for that. 
3. error banner is blue as well. You can observe it during deployment and click cancel button
4. Server details from discovered server...click tabs , then contents are blank.

**Comment by guglo** [comment]
some errors noticed when show message
react-dom.development.js:506 Warning: React does not recognize the `bsStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `bsstyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Alert)
    in Transition (created by Fade)
    in Fade (created by Alert)
    in Alert (created by Context.Consumer)
    in Uncontrolled(Component) (at src/index.js:127)
    in div (created by NotificationMessage)
    in NotificationMessage (created by ErrorMessage)
    in ErrorMessage (created by LoginPage)
    in div (created by LoginPage)
    in div (created by LoginPage)
    in LoginPage (created by Route)
    in Route (created by Deployer)
    in Switch (created by Deployer)
    in Router (created by HashRouter)
    in HashRouter (created by Deployer)
    in Deployer
    in AppContainer
warningWithoutStack @ react-dom.development.js:506
warning @ react-dom.development.js:2619
validateProperty$1 @ react-dom.development.js:7184
warnUnknownProperties @ react-dom.development.js:7225
validateProperties$2 @ react-dom.development.js:7245
validatePropertiesInDevelopment @ react-dom.development.js:7296
setInitialProperties @ react-dom.development.js:7545
finalizeInitialChildren @ react-dom.development.js:8603
completeWork @ react-dom.development.js:15558
completeUnitOfWork @ react-dom.development.js:17634
performUnitOfWork @ react-dom.development.js:17837
workLoop @ react-dom.development.js:17849
renderRoot @ react-dom.development.js:17935
performWorkOnRoot @ react-dom.development.js:18823
performWork @ react-dom.development.js:18735
performSyncWork @ react-dom.development.js:18709
requestWork @ react-dom.development.js:18578
scheduleWork @ react-dom.development.js:18387
enqueueSetState @ react-dom.development.js:12313
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:372
(anonymous) @ Login.js:89
Promise.catch (async)
LoginPage._this.handleLogin @ Login.js:82
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:270
executeDispatch @ react-dom.development.js:561
executeDispatchesInOrder @ react-dom.development.js:583
executeDispatchesAndRelease @ react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:688
forEachAccumulated @ react-dom.development.js:662
runEventsInBatch @ react-dom.development.js:816
runExtractedEventsInBatch @ react-dom.development.js:824
handleTopLevel @ react-dom.development.js:4820
batchedUpdates$1 @ react-dom.development.js:18918
batchedUpdates @ react-dom.development.js:2150
dispatchEvent @ react-dom.development.js:4899
interactiveUpdates$1 @ react-dom.development.js:18973
interactiveUpdates @ react-dom.development.js:2169
dispatchInteractiveEvent @ react-dom.development.js:4876
react-dom.development.js:506 Warning: Unknown event handler property `onDismiss`. It will be ignored.
    in div (created by Alert)
    in Transition (created by Fade)
    in Fade (created by Alert)
    in Alert (created by Context.Consumer)
    in Uncontrolled(Component) (at src/index.js:127)
    in div (created by NotificationMessage)
    in NotificationMessage (created by ErrorMessage)
    in ErrorMessage (created by LoginPage)
    in div (created by LoginPage)
    in div (created by LoginPage)
    in LoginPage (created by Route)
    in Route (created by Deployer)
    in Switch (created by Deployer)
    in Router (created by HashRouter)
    in HashRouter (created by Deployer)
    in Deployer
    in AppContainer

**Comment by guglo** [comment]
if page shows ok...console still shows some warning... 
react.development.js:225 Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?

**Comment by guglo** [comment]
@jeremy-moffitt  
1. I still have a nagging warnings related  to eact.development.js:225 Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
2. the success message is not green in connection dialog
3. the loading mask for dialog is a little bit shifted down, leave more white space
4 the assign sever role page in day0 and day2 emits some warnings related to render <Context> Directly , something related to tabs. observed similar when click the manage cloud in server summary and configure files page in day0
5. The server configured details indeed looks wired...it used to be more spread and centered. Same issue in master...so it is not caused by styling change. 
6 the server discovered details now seem to have more white space between each line. 
7. error banner is red now. You added a close button ...but I think it is fine.

**Comment by guglo** [comment]
BTW, the code base seems to be quite old..not sure if you need to rebase?

**Comment by jeremy-moffitt** [comment]
@guglo some of table spacing is tough to fix since bootstrap changed their default row height... I'll look into the other issues. Is there somewhere where the error messages aren't supposed to be dismissable? I thought they were before

**Comment by guglo** [comment]
if spacing is fine. 
error message is closable. 
error banner was not closable, but now is closable. think it is ok if it is closable.

**Comment by jeremy-moffitt** [comment]
@guglo  I cant find any references to Consumer.Consumer in our source :-/

fixed several of the issues, need to rebase

**Comment by jeremy-moffitt** [comment]
I think the modal and alert issues are fixed now, also rebased the changeset

**Comment by jeremy-moffitt** [comment]
need to re-rebase, and clean up some lints

**Comment by jeremy-moffitt** [comment]
updated, also fixed an error message panel issue with the rebase... should be ready for review again

**Comment by guglo** [comment]
ok, will take a look again

**Pull request merged**
