### PR TITLE
Fixed issue when remove role and delete server (SCRD-8719)

### PR DESCRIPTION
**Pull request by ghost**
This commit includes a couple of fixes in day0 and day2:

1. Cleaned up the logic to update server correctly in manually
added servers and discovered servers list when remove role
of a server (drag server to the left) in day0 and day2
2. Used the common function to remove server from model to avoid the
problem where it deletes server with -1 index.
3. Fixed missing sessionKey when click save and continue button
without click Test first.
4. Fixed lost check possible null values of model in day0

### CODE REVIEW

**Comment by guglo** [comment]
Please check https://jira.suse.de/browse/SCRD-8719 for what to test.

**Comment by jeremy-moffitt** [comment]
reproduced issue on master, tested fix and it works... still looking over the code

**Review by jeremy-moffitt — APPROVED** [review]
LGTM , I had to pick through the checkInputs change a bit, but looks good and solves the problem

**Review by eapodaca — APPROVED** [review]
LGTM. Works as expected.

**Pull request merged**
