### PR TITLE
Add keystone authorization UI

### PR DESCRIPTION
**Pull request by GarySmith**
Create modal dialog to prompt for credentials, and verify them against
keystone via the ardana-service.  Create functions and classes for
managing token information with cookies and injecting it into subsequent
REST calls.

### CODE REVIEW

**Comment by GarySmith** [comment]
Note that approach uses a modal dialog box for prompting for credentials, but modifying the whole routing approach may require adjusting this (see https://github.com/ArdanaCLM/ardana-installer-ui/pull/99)

**Comment by GarySmith** [comment]
This version incorporates the routing prototype from pull request #100 . Two things could still be improved, but are probably best handled in a separate change:
1. When initially navigating to the UI, the first page will briefly be displayed and then redirected to the login page. (fixing this would require some login in the wizard at startup to avoid this)
2. If a valid token times out when the user is inactive, this will not be detected until the user tries to perform some operation against the ardana-service. Instead it should be more like a banking website that automatically jumps to the login page when the time has elapsed even without any activity.

**Comment by GarySmith** [comment]
One additional note: this change introduces a new dependency, so the IBS job will need to be updated (to include a new node_modules tarball) with the new dependency. Failure to do so should not cause the build to fail, but if a user *were* to try to use the app in a day 2 scenario without this, then they would get an error in the browser

**Comment by jeremy-moffitt** [comment]
question about:
> When initially navigating to the UI, the first page will briefly be displayed and then redirected to the login page. (fixing this would require some login in the wizard at startup to avoid this)
could this be solved by displaying nothing until we check for the token?

**Comment by jeremy-moffitt** [comment]
I'm a bit confused, when I try to reproduce the problem described above (needing to click login twice) its not happening anymore... I'm not sure what changed

**Comment by GarySmith** [comment]
> could this be solved by displaying nothing until we check for the token?

I think so, and that's what I intend to do. I just didn't want this change to wait for me to get that implemented.

**Comment by GarySmith** [comment]
> I'm a bit confused, when I try to reproduce the problem described above (needing to click login twice) its not happening anymore... I'm not sure what changed

Same here. I was able to reproduce that for a time, but it seems to work flawlessly now. Strange.

**Pull request merged**
