### PR TITLE
Only show ses config upload option when ses is not configured (SOC-8555)

### PR DESCRIPTION
**Pull request by eapodaca**

### CODE REVIEW

**Comment by guglo** [comment]
@eapodaca  code looks good to me. Only think I found is when ses_config_path is set to somewhere, ses_config.yml is not available, loader will load file into config/ses folder instead of the ses_config_path. I am not familiar with ses integration not sure if the test case if a valid test case. Ethan will take a look.

**Comment by eapodaca** [comment]
Added a call to `/api/v2/ses/configure` to properly configure the `settings.yml` file to point to the location that the `ses_settings.yml` file will be uploaded.

**Comment by eapodaca** [comment]
This PR does not address the one renaming issue related to the mussing `ses-status.yml` file missing during day 0 install.

**Comment by guglo** [comment]
Retested...found some issues. Test cases in dev env: 

1. ses_config.yml is under my_cloud/config/ses - OK
#ses_config_path: <...>
No file loader
No change in settings.yml

2. ses_config.yml is NOT under  my_cloud/config/ses - OK
#ses_config_path: <...>
Have file loader, load file, ses_config.yml shows up under my_cloud/config/ses
No changes in settings.yml
After load file, no file loader anymore

3. ses_config.yml is under my_could/  - Have some issues
settings.yml has ses_config_path: ~/dev/day0React/ardana-service/data/my_cloud
Have file loader, load file , ses_config.yml shows up under my_cloud/config/ses
Note: the file is there, should not ask for load the file again. 

4. ses_config.yml is NOT under my_could/  -- Have some issues now ???
settings.yml has ses_config_path: ~/dev/day0React/ardana-service/data/my_cloud
Have file loader, load file, ses_config.yml shows up under my_cloud/config/ses
settings..yml has ses_config_path: ~/dev/day0React/ardana-service/data/my_cloud
reload the UI, the file loader shows up again....
Note: last time when I tested this case, settings.yml ses_config_path: data/my_cloud/config/ses. Not sure what is going on.

**Comment by GarySmith** [comment]
As mentioned in the update commit message, the upload button is present whenever the set settings.xml points to a file that is missing or does not contain valid yaml.
Another significant change is that the full path of the ses config file is added into the tree of config files whenever it is present (even if it is invalid).  So putting this together with the first item, if the settings.xml points to an invalid yml file, there is both an upload link available (to overwrite it), as well as a direct link to the file itself (to edit it).

**Comment by guglo** [comment]
retested Gary's changes: 

1. 
ses_config_path: /home/gugl/dev/day0React/ardana-service/data/my_cloud
Has  ses_config.yml
no file loader,  file shows up with actual path
able to update the  /home/gugl/dev/day0React/ardana-service/data/my_cloud/ses_config.xml
OK

2. ses_config_path: /home/gugl/dev/day0React/ardana-service/data/my_cloud
Has no ses_config.yml
file loader shows up, load file, file shows up with actual path
able to update the  /home/gugl/dev/day0React/ardana-service/data/my_cloud/ses_config.xml
OK

3. ses_config_path: data/my_cloud/config/ses
Has ses_config.yml
file shows up without path
able to update the ses_config.yml
OK

4. ses_config_path: data/my_cloud/config/ses
Has NO ses_config.yml
has file loader, load file, have bad request error. 
Failed

5. #ses_config_path: data/my_cloud/config/ses commented out 
Has NO ses_config.yml 
no file loader and the result of configure API is {'ses_configured': False, 'ses_config_path': None}
I assume if ses_config_path given, it takes default data/my_cloud/config/ses. But I am not sure. Please check. 

6.  #ses_config_path: data/my_cloud/config/ses commented out 
Has ses_config.yml 
file show up without path
the result of configure API is {'ses_configured': False, 'ses_config_path': None}
Please check 

7. Tested Others
update nova only - OK 
update nova + neutron - OK
update ses + nova  - OK
update above with encrypt key - OK

**Comment by GarySmith** [comment]
Thanks for testing. It is important to know that relative paths (like data/my_cloud/config/ses) are not supported by the ses playbooks, and if you were to try to use them, the results would be unpredictable, since in the UI it would be relative to the cwd of the ardana-service, and for the playbooks it would be relative to the cwd of wherever the user happened to be when they launched the playbook.

**Comment by GarySmith** [comment]
> 5. #ses_config_path: data/my_cloud/config/ses commented out
>    Has NO ses_config.yml
>    no file loader and the result of configure API is {'ses_configured': False, 'ses_config_path': None}
>    I assume if ses_config_path not given, it takes default data/my_cloud/config/ses, but I am not sure. 
No, neither the UI nor the playbook assumes that the ses_config_path or the ses_config_file has a default value (see [1] for example); instead both the UI and the ses playbooks require both values to be set in order for ses to be enabled. See also [2], which throws a failure unless both are set.

[1] http://git.ci.prv.suse.net/cgit/ardana/ardana-extensions/ses/tree/roles/ses_common/library/load_ses_config.py#n51
[2] http://git.ci.prv.suse.net/cgit/ardana/ardana-extensions-ses/tree/roles/ses_common/library/load_ses_config.py#n83

**Comment by guglo** [comment]
@GarySmith  so test case 3, 4, 5, 6 are not supported. settings.xml need to have pull path of ses_config_path available. Ok I accept that.

**Comment by GarySmith** [comment]
> @GarySmith so test case 3, 4, 5, 6 are not supported. settings.xml need to have pull path of ses_config_path available. Ok I accept that.

Correct, test cases with relative paths are not supported. Of course, as you found, you can specify an absolute path to the same location. BTW the value suggested in the documentation is `/var/lib/ardana/ses/` (page 338 of https://www.suse.com/documentation/suse-openstack-cloud-8/pdfdoc/book_installation/book_installation.pdf)

**Comment by guglo** [comment]
@GarySmith  thanks for the clarification.

**Pull request merged**
