### PR TITLE
Simplify components and convert to stateless functions

### PR DESCRIPTION
**Pull request by GarySmith**
Remove unnecessary state and convert to stateless functional components

### CODE REVIEW

**Comment by guglo** [comment]
Noticed regression forListDropDown.: When AddServer manually Nic-mapping and role select doesn't seem to select.

**Comment by GarySmith** [comment]
Grrr. It works for edit mode but not add mode. The problem is that a number of variables in this ServersAddedManually belong in state and are not there (those that the user has entered and should trigger re-rendering when changed). I'll fix this dialog too

**Comment by GarySmith** [comment]
I found a bug in the refresh logic that supressed updates when in add mode and submitted that. Cleaning up the state can wait for another time.

**Comment by guglo** [comment]
@GarySmith  Not sure it is ready, but I tried the latest change, AddServerManually modal now allows me select now, but the buttons don't get enabled.

**Comment by GarySmith** [comment]
OK, I tested this dialog in many ways, and it works correctly in every way I tried. @guglo can you break it?

**Comment by guglo** [comment]
@GarySmith  ok will give it a try :)

**Comment by GarySmith** [comment]
Thanks for testing it and spotting the lint warnings (my auto-lint-checking plugin in vim was temporarily disabled and I missed those).

**Pull request merged**
