### PR TITLE
Fix logic errors preventing migration on deactivate

### PR DESCRIPTION
**Pull request by eapodaca**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
@eapodaca  I found the issue when I tested retry in 3nodes...I had the fix in https://github.com/ArdanaCLM/ardana-installer-ui/pull/317 which I am still testing , but I am happy to take yours.

**Comment by eapodaca** [comment]
Alright, we cab take yours.

**Comment by guglo** [comment]
@eapodaca  I can take yours...since your PR is quicker.

**Comment by eapodaca** [comment]
Closing again.

**Pull request closed without merging**
