### PR TITLE
SCRD-6838, SCRD-4498 on complete show links

### PR DESCRIPTION
**Pull request by eapodaca**
Get links for complete screen from the keystone catalog.

### CODE REVIEW

**Comment by GarySmith** [comment]
> Note that this won't work for astack deployments, but does produce the correct Horizon URL for "real" deployments. 

Can you elaborate on that a bit?

> ...figuring out why the config file is missing the values in the first place

If you are referring to the ardana service config file, the reason it does not have these values is that they are only populated in the config file by the config processor, which is run as part of the deployment page, and they are not available to the ardana-service until it is restarted or the config file is forceably re-read, at which point the ardana service would be listening on another interface that is not available to the UI, etc.

**Comment by jeremy-moffitt** [comment]
> > Note that this won't work for astack deployments, but does produce the correct Horizon URL for "real" deployments.
> 
> Can you elaborate on that a bit?

on an astack system the urls show up as `https://myardana.test:443` which doesn't help the user at all

**Comment by jeremy-moffitt** [comment]
based on Garys comment about the config processor, reading these from keystone and trimming the ops console URL may be the most reliable approach... so that should be a modest tweak from the current version of this change

**Comment by eapodaca** [comment]
This change should be trimming the path for both horizon and the opsconsole urls. As an alternative we could have the service request for the endpoints read and parse the config file from disk.

**Comment by jeremy-moffitt** [comment]
The astack fix worked, not sure I understand how the trimming is taking place (note that the Horizon url is correct coming out of keystone)

**Comment by guglo** [comment]
@eapodaca  question, when keystone is up...in day0 do we need to use user/pass to access endpoint list?

**Comment by eapodaca** [comment]
@jeremy-moffitt please re-review this has drastically changed since you reviewed it last.

I have updated the `/api/v2/external_urls` `ardana-service` endpoint to return the urls from the internal model.

**Comment by jeremy-moffitt** [comment]
@eapodaca does this require https://gerrit.suse.provo.cloud//#/c/5590/  to have landed to function?

**Comment by eapodaca** [comment]
> @eapodaca does this require https://gerrit.suse.provo.cloud//#/c/5590/ to have landed to function?

Not required but with that change the bugs are 100% fixed.

**Comment by jeremy-moffitt** [comment]
tried this out with the gerrit change, and it does load the links... but it takes some time... at first I thought it was broken, but after waiting it out, the links did show up eventually.

**Comment by jeremy-moffitt** [comment]
overall this looks ok to me, though its taking 10 seconds to load the links, so if that time to load cant be reduced, then we should put a loading indicator of some sort where the "useful links" are (I'm hesitant to mask off the modal as it wouldnt be very obvious why thats happening)...  open to ideas... maybe "Loading useful links..." that changes into the current "Useful links:" section.

**Pull request merged**
