### PR TITLE
Hide undeployed servers in the servers page in day2 production (SCRD-6682)

### PR DESCRIPTION
**Pull request by ghost**
…6682)

### CODE REVIEW

**Review by eapodaca — APPROVED** [review]
LGTM

**Review by jeremy-moffitt — CHANGES_REQUESTED** [review]
The code looks fine, but when I tried this out, I still see the "replace" action on the compute server I added but haven't deployed yet

**Comment by guglo** [comment]
@jeremy-moffitt you should not see any changes in dev, hide is only for production.  Just need to leave some convenient for dev testing.

**Comment by guglo** [comment]
If force production in dev, when just drag a server in compute without run deploy...that server will NOT show up in server summary page day2.  however in day0, it should show up. 
 export function isProduction() {
  if (PRODUCTION) { // eslint-disable-line no-undef
    return true;
  }
  return true;
}

If NOT force production, then it will show up in the server summary in day2, no restriction there.

**Comment by jeremy-moffitt** [comment]
@guglo sorry for the delay, trying it out now in production mode

**Review by jeremy-moffitt — APPROVED** [review]

**Comment by jeremy-moffitt** [comment]
I see the filter applying in production mode (the server does appear, but is quickly filtered out), thanks!

**Pull request merged**
