### PR TITLE
Add control plane topology page

### PR DESCRIPTION
**Pull request by GarySmith**
Add the control plane page into the topology section of the menu.  This
page is very close to the control plane page that is emitted by the
configuration processor.

### CODE REVIEW

**Comment by GarySmith** [comment]
Note that some of the fields are created as html links in order to mimic the config processor page, but these links are not (yet) valid since the other topology pages have not been created.  These links will be updated when those pages are created.

**Comment by GarySmith** [comment]
I hadn't planned to put boxes since we are not using them anywhere in the app so far. These could be added.
The long load is due to the fact that the file that is loaded on the back end is pretty large (the midsize model's is more then 6MB). As an performance improvement I plan to be able to load it once and share it between the various topology tabs to avoid the delays.

**Comment by jeremy-moffitt** [comment]
Hmm ok, I'll have to look at it again, having seen the previous version I thought that the groupings from the boxes made it more obvious which things were associated with each other... on the performance thing, I wonder if we could compress the file before sending it across the wire

**Comment by GarySmith** [comment]
The compression *may* help a bit, but I think the bulk of the time is actually spent loading the file, converting the file into python, than converting it into json to be sent. As a test, I have a little program that does those steps without actually transferring the file, and it takes about 7.9 seconds to do just that. The UI actually only waits 8.1 seconds, so I think the transfer time is only about 0.2 seconds.

Agreed on the boxes and grouping. At this point I was more concerned with being able to reproduce all of the data and leaving the details of formatting for later. I guess I should have been more clear on that. I think we still probably need to talk through this formatting and decide what is best before reproducing those odd boxes and and shading in the existing html.

**Pull request merged**
