### PR TITLE
Prevent manipulating servers during op progress (SCRD-8553)

### PR DESCRIPTION
**Pull request by ghost**
Prevent editing/deleting/moving servers with roles in AddServer when replacing a server in progress

### CODE REVIEW

**Review by eapodaca — APPROVED** [review]
LGTM. Did not test.

**Review by GarySmith — APPROVED** [review]
Ditto. LGTM but did not test

**Review by dotNomad — CHANGES_REQUESTED** [review]
While replacing a compute server was able to navigate to Add Server, but I noticed a few issues.

- If I manually add a new server and drag it over, the previously deployed compute servers become read only. If I then deploy the other servers are still stuck in read only mode. I can't seem to find a way to unlock them so they can be edited or deleted again.
Upon further testing this appears to happen if just importing servers from a CSV file.

- While the dragging is disabled it is possible to still drag the servers by highlighting their text, and dragging the highlighted text. This is fairly easy to "accidentally" do if you expect them to drag as when you do and they are disabled the text will be highlighted.

**Review by jeremy-moffitt — APPROVED** [review]
tried it out, this worked fine after learning how to test it :)

**Comment by dotNomad** [comment]
Sounds like it is expected to have previously deployed compute servers be read only. Approving, and opening a separate issue for the dragging highlighted text bug.

**Review by dotNomad — APPROVED** [review]

**Comment by guglo** [comment]
Talked Jordan , the deployed servers are not allowed to edit and delete by default in Add Servers, unless user uncheck the safe mode. Regarding the drag and drop, it is more of the drag and drop component issue, Jordan will file a defect for that issue.

**Pull request merged**
