### PR TITLE
Add button to copy server details (SCRD-8243)

### PR DESCRIPTION
**Pull request by eapodaca**
* Add button to copy server details from server to be replaced.
* Refactor some common copy code from available servers functionality.

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
Seems to work ok... still deciding if the button in the top right is the best "affordance" to use for this... but not sure a better alternative at the moment

**Comment by eapodaca** [comment]
I wasn't sure about that either, looks equally strange on the left also.

**Comment by guglo** [comment]
@eapodaca  replacing a compute node is to add a new compute node and delete the old compute . If user enter the information manually ...all the information will be saved into manually added servers. If replace failed, the server will be in manually added server and if user want to try again, they can use select from available servers to pick up the info they entered.  If still want to have this copy button in replace compute dialog, it needs to coordinate with select from available servers and make sure some fields have no conflict with the existing ones and no copy of password. 

In replace a controller, it only replaces IPMI stuffs, not sure the info will be saved into manual servers. If want to want to copy from existing ones, it needs to coordinate with select from available servers and make sure some fields have no conflict with the existing ones and no copy of password. 

At this point I think it is not a good idea to have the copy button there.

**Comment by eapodaca** [comment]
Alright if there is a way for users to move forward and not get stuck I am fine with this. Closing.

**Pull request closed without merging**
