### PR TITLE
Fixed issue when installation progress.json is present

### PR DESCRIPTION
**Pull request by ghost**
If progress.json left from installation, the steps could mess up the servers page loading in day2UI, add a restriction for day2UI progress loading.

### CODE REVIEW

**Review by jeremy-moffitt — APPROVED** [review]
LGTM, tried it out and seemed to work ok... though I'm not 100% clear what the change is... only interpret the progress if currentMenuName is set... it definitely works, I just dont understand how

**Comment by guglo** [comment]
@jeremy-moffitt when loadUpdateProgress, if there is no currentMenuName to present...then it treats as there are no progresses and no steps so it will ignore the steps left from installation.  when user starts replace process in Day2UI, it records the currentMenuName into the progress  and record its own progress stuffs (steps, playbooks...).

**Review by GarySmith — COMMENTED** [review]
While this fix seems to work, it deserves some kind of explanation in the code about what this odd check is for.

**Comment by guglo** [comment]
@GarySmith, ok since Jeremy also asks the question, I will add some comments at the code.

**Comment by guglo** [comment]
@GarySmith  Are you happy with the comments update? Since can not rocketchat guess ping you here :)

**Review by GarySmith — APPROVED** [review]
Thanks for adding the explanation. Looks great.

**Pull request merged**
