### PR TITLE
Use Lato font version 2.015 from latofonts.com

### PR DESCRIPTION
**Pull request by eapodaca**
This moves us to the latest version of the lato font downloaded from Google's server. This helps drastically with the vertical centering issue.

### CODE REVIEW

**Comment by eapodaca** [comment]
There should be a PR for crowbar-core with that. 

On April 15, 2019 11:37:29 AM PDT, Jeremy Moffitt <notifications@github.com> wrote:
>jeremy-moffitt approved this pull request.
>
>looks good, fixes the spacing issue, we should try to get this into the
>crowbar UI as well... though given the timing we should probably wait
>to merge this until the MU
>
>
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ArdanaCLM/ardana-installer-ui/pull/349#pullrequestreview-226813858

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeremy-moffitt** [comment]
I didnt realize the crowbar version was included in https://github.com/crowbar/crowbar-core/pull/1837

if theres another build we'll include this, otherwise in the first MU

**Comment by dotNomad** [comment]
Updated to include the Lato font with the full character set, and a bit of a work around for the vertical centering issue on buttons.

**Comment by guglo** [comment]
@eapodaca  I noticed the modal of edit server and replace compute, the dropdown is much thinner and the buttons (server group and nic mapping) at the right side of the dropdowns seem to be too big now.  You can see modal with the dropdowns from Add Server -> Add Server manually or  Summary  -> replace a compute.

**Comment by dotNomad** [comment]
@guglo Great catch. I can add a commit to the PR to fix this :+1:

**Pull request merged**
